"""new

Revision ID: c09208101dbe
Revises: 
Create Date: 2020-06-09 03:22:13.100996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c09208101dbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_title', sa.Unicode(length=300), nullable=True),
    sa.Column('post_content', sa.Unicode(length=5000), nullable=True),
    sa.Column('post_date_gmt', sa.DateTime(), nullable=True),
    sa.Column('post_excerpt', sa.Unicode(length=200), nullable=True),
    sa.Column('original_link', sa.Unicode(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engine_post_date_gmt'), 'engine', ['post_date_gmt'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_engine_post_date_gmt'), table_name='engine')
    op.drop_table('engine')
    # ### end Alembic commands ###
